FROM golang:latest AS builder

WORKDIR /app

COPY . .

RUN go install

RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o main main.go

FROM alpine:3.21

COPY --from=builder /app/main .

EXPOSE 8080

CMD ["./main"]